version: "3"
tasks:
  all:
    desc: Install Rust and all required crates
    cmds:
      - task: all:deps
      - task: all:crates
  all:deps:
    desc: Install rustc and cargo
    cmds:
      - cargo -V || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  all:crates:
    desc: Install required cargo packages
    cmds:
      - for:
          - taplo-cli
          - git-delta
          - fd-find
        cmd: cargo install --list | grep -w {{.ITEM}} || cargo install {{.ITEM}}
