# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  all:
    desc: Install Hammerspoon plugins
    cmds:
      - task: all:spoons
  all:spoons:
    desc: Install Spoons
    status:
      - test -d ${DOTFILES_HOME}/hammerspoon/Spoons/Ki.spoon
      - test -d ${DOTFILES_HOME}/hammerspoon/Spoons/VimMode.spoon
      - test -d ${DOTFILES_HOME}/hammerspoon/Spoons/SpoonInstall.spoon
    cmds:
      - bash <(curl -s https://raw.githubusercontent.com/dbalatero/VimMode.spoon/master/bin/installer)
