# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
dotenv: [".env"]
vars:
  SHELL: /usr/bin/env bash -o pipefail
  DOTFILES_HOME: "${HOME}/.dotfiles"
  DOTFILES_CONFIG: "${DOTFILES_HOME}/etc/config"
  DOTFILES_PROFILE: "${DOTFILES_HOME}/etc/profile"
  DOTFILES_RC: "${DOTFILES_HOME}/etc/rc"
  DOTFILES_SCRIPTS: "${DOTFILES_HOME}/scripts"
includes:
  macos:install:brew:
    taskfile: ./tasks/macos/install/brew/Taskfile.yml
  macos:install:core:
    taskfile: ./tasks/macos/install/core/Taskfile.yml
  macos:install:docker:
    taskfile: ./tasks/macos/install/docker/Taskfile.yml
  macos:install:java:
    taskfile: ./tasks/macos/install/java/Taskfile.yml
  macos:install:hammerspoon:
    taskfile: ./tasks/macos/install/hammerspoon/Taskfile.yml
tasks:
  default:
    cmds:
      - task: list
    silent: true
  list:
    desc: Lists available commands
    cmds:
      - task -l
  hooks:
    desc: Setup git hooks locally
    cmds:
      - cp scripts/hooks/* .git/hooks/
    silent: true
  precommit:
    desc: Verifies and fix requirements for new commits
    cmds:
      - scripts/hooks/pre-commit
  changelog:
    silent: true
    desc: Generates CHANGELOG
    cmds:
      - echo "Updating Changelog"
      - cmd: |-
          git cliff --context \
          | jq '.[].commits.[] |= (. + {extra: {date: ( .committer.timestamp | strftime("%Y-%m-%d") )}} ) | sort_by(.commits.[].commit.committer.timestamp)' \
          | jq -S 'walk(if type == "array" then sort_by(.timestamp) | reverse else . end)' \
          | git cliff --from-context - > CHANGELOG.md
      - cmd: git add {{.USER_WORKING_DIR}}/CHANGELOG.md
  macos:install:all:
    desc: Install all MacOS required tools
    cmds:
      - task: macos:install:brew:all
      - task: macos:install:core:all
      - task: macos:install:docker:all
      - task: macos:install:go:all
      - task: macos:install:k8s:all
      - task: macos:install:java:all
      - task: macos:install:npm:all
      - task: macos:install:python:all
      - task: macos:install:rust:all
