[[manager.prepend_keymap]]
on = "<C-s>"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on = "K"
run = "plugin --sync parent-arrow --args=-1"

[[manager.prepend_keymap]]
on = "J"
run = "plugin --sync parent-arrow --args=1"

[[manager.prepend_keymap]]
on = ["c", "y"]
run = "yank"
desc = "Copy the selected file(s)"
