#!/bin/bash

# Get latest version
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

# Set permission
chmod 755 kubectl

# Move to bin
sudo mv ./kubectl /usr/local/bin/kubectl

