#!/bin/bash

DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H%M%S")
CONN_NUMBER=$(netstat -an | grep -v grep | wc -l)
echo "$DATE@$TIME@TOTAL@$CONN_NUMBER"

for CONN_TYPE in $(netstat -an | awk '{print $6}'  | sort -u| egrep -v '[a-z]' | grep  ^'[A-Z]' | grep -v grep)
do
   CONN_NUMBER=$(netstat -an | grep "$CONN_TYPE" | grep -v grep| wc -l)
   echo "$DATE@$TIME@$CONN_TYPE@$CONN_NUMBER"
done

