# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  all:
    desc: Install Docker and container related tooling
    cmds:
      - task: rancher
      - task: buildx
  rancher:
    desc: Install Rancher Desktop
    status:
      - rdctl version
    cmds:
      - curl -o /tmp/Rancher.Desktop-1.14.1.aarch64.dmg https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.14.1/Rancher.Desktop-1.14.1.aarch64.dmg | open /tmp/Rancher.Desktop-1.14.1.aarch64.dmg
  buildx:
    desc: Install Docker Buildx
    status:
      - docker buildx version
    cmds:
      - curl -o "${HOME}/.docker/cli-plugins/docker-buildx" https://github.com/docker/buildx/releases/download/v0.15.0/buildx-v0.15.0.darwin-amd64
      - chmod a+x "${HOME}/.docker/cli-plugins/docker-buildx"
      - docker buildx version
