version: "3"
tasks:
  all:
    desc: Brew install all packages
    cmds:
      - task: all:deps
      - task: all:regular
      - task: all:custom
      - task: all:fonts
  all:deps:
    desc: Install Brew itself along with some important libs and repos
    vars:
      DOWNLOAD_URL: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    status:
      - brew --version
    cmds:
      - /bin/bash -c "$(curl -fsSL {{.DOWNLOAD_URL}})"
      - brew list | grep -w readline || brew install readline zlib
      - brew list | grep -w zlib || brew install zlib
      - brew tap fluxcd/tap
      - brew tap knqyf263/pet
      - brew tap aquasecurity/trivy
      - brew tap arl/arl
  all:regular:
    desc: Brew install regular recipes
    cmds:
      - for:
          - aquasecurity/trivy/trivy
          - bash
          - bufbuild/buf/buf
          - chafa
          - choose-gui
          - coreutils
          - erlang
          - fd
          - ffmpegthumbnailer
          - font-hack-nerd-font
          - font-symbols-only-nerd-font
          - gitmux
          - gnu-sed
          - go-task/tap/go-task
          - gpg
          - grc
          - htop
          - iftop
          - imagemagick
          - jq
          - knqyf263/pet/pet
          - kubent
          - lazygit
          - luajit
          - luarocks
          - maczip
          - markdown-toc
          - moreutils
          - pass
          - php
          - pipx
          - poppler
          - pre-commit
          - ripgrep
          - sevenzip
          - sops
          - source-highlight
          - terminal-notifier
          - the_silver_searcher
          - tmux
          - tmuxp
          - ueberzugpp
          - viu
          - vlc
          - wezterm
          - wget
          - xz
          - yazi
          - yq
          - zoxide
        cmd: brew list {{.ITEM}} || brew install {{.ITEM}}
  all:fonts:
    desc: Install Nerd-Fonts
    cmds:
      - |
        set -e
        for FONT in $(cat ${DOTFILES_HOME}/etc/lists/fonts.txt); do
          brew install "${FONT}"
        done
  all:custom:
    desc: Brew install recipes with custom steps
    dotenv:
      - ~/.zshrc
    cmds:
      - test -f /Applications/Amethyst.app/Contents/MacOS/Amethyst || brew install --cask amethyst
      - task: all:custom:colima
  all:custom:colima:
    desc: Brew install Colima
    dotenv:
      - ~/.zshrc
    status:
      - command -v $(which colima)
    cmds:
      - brew install colima
      - brew services start colima
