version: "3"
tasks:
  all:
    desc: Brew install all packages
    cmds:
      - task: all:deps
      - task: all:regular
      - task: all:custom
  all:deps:
    desc: Install Brew itself along with some important libs and repos
    vars:
      DOWNLOAD_URL: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    status:
      - brew --version
    cmds:
      - /bin/bash -c "$(curl -fsSL {{.DOWNLOAD_URL}})"
      - brew list | grep -w readline || brew install readline zlib
      - brew list | grep -w zlib || brew install zlib
      - brew tap fluxcd/tap
      - brew tap knqyf263/pet
      - brew tap aquasecurity/trivy
      - brew tap arl/arl
  all:regular:
    desc: Brew install regular recipes
    cmds:
      - for:
          - bash
          - coreutils
          - moreutils
          - wget
          - terminal-notifier
          - xz
          - gnu-sed
          - jq
          - yq
          - imagemagick
          - tmux
          - tmuxp
          - gitmux
          - pipx
          - gpg
          - pass
          - lazygit
          - choose-gui
          - sops
          - htop
          - iftop
          - source-highlight
          - the_silver_searcher
          - ripgrep
          - font-hack-nerd-font
          - knqyf263/pet/pet
          - go-task/tap/go-task
          - pre-commit
          - grc
          - luarocks
          - luajit
          - viu
          - chafa
          - aquasecurity/trivy/trivy
          - ueberzugpp
          - erlang
        cmd: brew list {{.ITEM}} || brew install {{.ITEM}}
  all:custom:
    desc: Brew install recipes with custom steps
    dotenv:
      - ~/.zshrc
    cmds:
      - test -f /Applications/Amethyst.app/Contents/MacOS/Amethyst || brew install --cask amethyst
      - test -f $(which skhd) || brew install koekeishiya/formulae/skhd && skhd --start-service
      - task: all:custom:colima
      - task: all:custom:packer
  all:custom:colima:
    desc: Brew install Colima
    dotenv:
      - ~/.zshrc
    status:
      - command -v $(which colima)
    cmds:
      - brew install colima
      - brew services start colima
  all:custom:packer:
    desc: Install Packer
    dotenv:
      - ~/.zshrc
    status:
      - command -v $(which packer)
    cmds:
      - brew tap hashicorp/tap
      - brew install hashicorp/tap/packer
