version: "3"
tasks:
  all:
    desc: Setup shell, core settings and tools
    cmds:
      - task: rosetta
      - task: fzf
      - task: nvim
      - task: profile
  rosetta:
    desc: Install Rosetta2
    status:
      - test -f /usr/libexec/rosetta/oahd
    cmds:
      - /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  fzf:
    desc: Install FuzzyFinder
    status:
      - test -d "${HOME}/.fzf"
    cmds:
      - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      - ~/.fzf/install --bin
  nvim:
    desc: Install NVIM nightly build
    status:
      - nvim --version | grep LuaJIT
    vars:
      NVIM_INSTALLER: ~/Downloads/nvim-macos-arm64.tar.gz
      NVIM_INSTALL_PATH: /opt/nvim
      NVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
    cmds:
      - nvim -version || curl -fsSL -o {{.NVIM_INSTALLER}} {{.NVIM_DOWNLOAD_URL}}
      - test nvim || sudo tar xzvf {{.NVIM_INSTALLER}} -C {{.NVIM_INSTALL_PATH}}
      - nvim -v || sudo chmod +x {{.NVIM_INSTALL_PATH}}/bin/nvim
  profile:
    desc: Setup shell profile settings
    cmds:
      - task: profile:createdirs
      - task: profile:links
      - task: profile:setup
  profile:links:
    cmds:
      - test -L ~/go/src                              || ln -s ~/git ~/go/src
      - test -L ~/.config/nvim                        || ln -s ${DOTFILES_HOME}/nvim ~/.config/nvim
      - test -L ~/.tmux.conf                          || ln -s ${DOTFILES_CONFIG}/tmux.conf ~/.tmux.conf
      - test -f ~/.tmux/plugins/tmux-fzf/plugin.tmux  || ln -s ${DOTFILES_SCRIPTS}/tmux-fzf-plugin.tmux ~/.tmux/plugins/tmux-fzf/plugin.tmux
      - test -L ~/pass-secret.sh                      || ln -s ${DOTFILES_SCRIPTS}/pass-secret.sh ~/pass-secret.sh
      - test -L ~/pass-user.sh                        || ln -s ${DOTFILES_SCRIPTS}/pass-user.sh ~/pass-user.sh
      - test -L ~/.config/pet/config.toml             || ln -s ${DOTFILES_CONFIG}/pet-config.toml ~/.config/pet/config.toml
      - test -L  ~/.amethyst.yml                      || ln -s ${DOTFILES_CONFIG}/amethyst.yml ~/.amethyst.yml
      - test -L ~/.skhdrc                             || ln -s ${DOTFILES_CONFIG}/skhd/skhdrc ~/.skhdrc
  profile:createdirs:
    cmds:
      - for:
          - ~/.config/pet
          - ~/.config/skhd
          - ~/.tmux/plugins/tmux-fzf
          - ~/git
          - ~/go
        cmd: mkdir -p {{.ITEM}}
  profile:setup:
    status:
      - diff ~/.zshrc ${DOTFILES_RC}/zshrc
      - test -L ~/.zshrc
    cmds:
      - mv ~/.zshrc ~/.zshrc_$(date -date +"%Y%m%d%s").bak || true
      - ln -s ${DOTFILES_RC}/zshrc ~/.zshrc
