version: "3"
tasks:
  all:
    desc: Setup shell, core settings and tools
    cmds:
      - task: fzf
      - task: kitty
      - task: nvim
      - task: links
  fzf:
    desc: Install FuzzyFinder
    cmds:
      - test -d "${HOME}/.fzf" || git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      - ~/.fzf/install --bin
  kitty:
    desc: Install Kitty terminal
    cmds:
      - test kitty || curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  nvim:
    desc: Install NVIM nightly build
    vars:
      NVIM_INSTALLER: ~/Downloads/nvim-macos-arm64.tar.gz
      NVIM_INSTALL_PATH: /opt/nvim
      NVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
    cmds:
      - nvim -version || curl -fsSL -o {{.NVIM_INSTALLER}} {{.NVIM_DOWNLOAD_URL}}
      - test nvim || sudo tar xzvf {{.NVIM_INSTALLER}} -C {{.NVIM_INSTALL_PATH}}
      - nvim -v || sudo chmod +x {{.NVIM_INSTALL_PATH}}/bin/nvim
  links:
    desc: Setup shell config links
    cmds:
      - mkdir -p ~/.config/pet ~/.config/skhd ~/.config/kitty
      - rm ~/.zshrc && ln -s ~/.dotfiles/config/zshrc ~/.zshrc
      - test -d ~/.config/nvim || ln -s ~/.dotfiles/nvim ~/.config/nvim
      - test -f ~/.tmux.conf || ln -s ~/.dotfiles/config/tmux.conf ~/.tmux.conf
      - test -f ~/.config/kitty/kitty.conf || ln -s ~/.dotfiles/config/kitty.conf ~/.config/kitty/kitty.conf
      - test -f ~/pass-secret.sh || ln -s ~/.dotfiles/scripts/pass-secret.sh ~/pass-secret.sh
      - test -f ~/pass-user.sh || ln -s ~/.dotfiles/scripts/pass-user.sh ~/pass-user.sh
      - test -f ~/.config/pet/config.toml ||  ln -s ~/.dotfiles/config/pet-config.toml ~/.config/pet/config.toml
      - test -f  ~/.amethyst.yml || ln -s ~/.dotfiles/config/amethyst.yml ~/.amethyst.yml
      - test -f ~/.skhdrc || ln -s ~/.dotfiles/config/skhd/skhdrc ~/.skhdrc
