# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  all:
    desc: Setup shell, core settings and tools
    cmds:
      - task: rosetta
      - task: fzf
      - task: nvim
      - task: profile

  rosetta:
    desc: Install Rosetta2
    status:
      - test -f /usr/libexec/rosetta/oahd
    cmds:
      - /usr/sbin/softwareupdate --install-rosetta --agree-to-license

  fzf:
    desc: Install FuzzyFinder
    status:
      - test -d "${HOME}/.fzf"
    cmds:
      - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      - ~/.fzf/install --bin

  nvim:
    desc: Install NVIM nightly build
    status:
      - nvim --version | grep LuaJIT
    vars:
      NVIM_INSTALLER: ~/Downloads/nvim-macos-arm64.tar.gz
      NVIM_INSTALL_PATH: /opt/nvim
      NVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-arm64.tar.gz
    cmds:
      - nvim -version || curl -fsSL -o {{.NVIM_INSTALLER}} {{.NVIM_DOWNLOAD_URL}}
      - test nvim || sudo tar xzvf {{.NVIM_INSTALLER}} -C {{.NVIM_INSTALL_PATH}}
      - nvim -v || sudo chmod +x {{.NVIM_INSTALL_PATH}}/bin/nvim

  profile:
    desc: Setup shell profile settings
    cmds:
      - task: profile:createdirs
      - task: profile:links
      - task: profile:setup

  profile:links:
    deps:
      - profile:createdirs
    cmds:
      - test -L ~/go/src                              || ln -s ~/git ~/go/src
      - test -L ~/.config/nvim                        || ln -s ${DOTFILES_HOME}/nvim ~/.config/nvim
      - test -L ~/.config/yazi                        || ln -s ${DOTFILES_HOME}/yazi ~/.config/yazi
      - test -L ~/.tmux.conf                          || ln -s ${DOTFILES_CONFIG}/tmux/tmux.conf ~/.tmux.conf
      - test -L ~/.amethyst.yml                       || ln -s ${DOTFILES_CONFIG}/amethyst.yml ~/.amethyst.yml
      - test -L ~/.config/terminalizer                || ln -s ${DOTFILES_CONFIG}/terminalizer.yaml ~/.config/terminalizer/config.yaml
      - test -L ~~/.p10k.zsh                          || ln -s ${DOTFILES_CONFIG}/p10k.zsh ~/.p10k.zsh
      - test -L ~/.config/atuin/config.toml           || ln -s ${DOTFILES_CONFIG}/atuim.toml ~/config/atuin/config.toml
      - cmd: |
          test -L ~/Library/Application\ Support/lazygit/config.yml \
          || ln -s ~/.dotfiles/etc/config/lazy.yaml ~/Library/Application\ Support/lazygit/config.yml

  profile:createdirs:
    cmds:
      - for:
          - ~/.config/atuin
          - ~/.config/terminalizer
          - ~/git
          - ~/go
          - ~/Library/Application\ Support/lazygit
        cmd: mkdir -p {{.ITEM}}

  profile:setup:
    status:
      - diff ~/.zshrc ${DOTFILES_RC}/zshrc
      - test -L ~/.zshrc
    cmds:
      - mv ~/.zshrc ~/.zshrc_$(date -date +"%Y%m%d%s").bak || true
      - ln -s ${DOTFILES_RC}/zshrc ~/.zshrc
