# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  all:
    desc: Setup shell, core settings and tools
    cmds:
      - task: rosetta
      - task: mise
      - task: fzf
      - task: nvim
      - task: profile

  rosetta:
    desc: Install Rosetta2
    status:
      - test -f /usr/libexec/rosetta/oahd
    cmds:
      - /usr/sbin/softwareupdate --install-rosetta --agree-to-license

  mise:
    desc: Installs mise-en-place
    status:
      - mise doctor
      - test -L ${HOME}/.config/mise/config.toml
    cmds:
      - curl https://mise.run | sh
      - set -ex
      - mkdir -p "${HOME}/.config/mise"
      - ln -sfv "${DOTFILES_HOME}/mise/config.toml" "${HOME}/.config/mise/config.toml"
      - mise plugin update
      - mise install -y
      - mise up -y

  fzf:
    desc: Install FuzzyFinder
    status:
      - test -d "${HOME}/.fzf"
    deps:
      - mise
    cmds:
      - mise install fzf@latest

  nvim:
    desc: Install NVIM nightly build
    status:
      - nvim --version | grep LuaJIT
    deps:
      - mise
    cmds:
      - mise install neovim@nightly

  profile:
    desc: Setup shell profile settings
    cmds:
      - task: profile:createdirs
      - task: profile:links
      - task: profile:setup
  profile:links:
    cmds:
      - test -L ~/go/src                              || ln -s ~/git ~/go/src
      - test -L ~/.config/nvim                        || ln -s ${DOTFILES_HOME}/nvim ~/.config/nvim
      - test -L ~/.tmux.conf                          || ln -s ${DOTFILES_CONFIG}/tmux/tmux.conf ~/.tmux.conf
      - test -L ~/.config/pet/config.toml             || ln -s ${DOTFILES_CONFIG}/pet-config.toml ~/.config/pet/config.toml
      - test -L ~/.amethyst.yml                       || ln -s ${DOTFILES_CONFIG}/amethyst.yml ~/.amethyst.yml
      - test -L ~/.config/terminalizer                || ln -s ${DOTFILES_CONFIG}/terminalizer.yaml ~/.config/terminalizer/config.yaml
  profile:createdirs:
    cmds:
      - for:
          - ~/.config/pet
          - ~/.config/terminalizer
          - ~/git
          - ~/go
        cmd: mkdir -p {{.ITEM}}
  profile:setup:
    status:
      - diff ~/.zshrc ${DOTFILES_RC}/zshrc
      - test -L ~/.zshrc
    cmds:
      - mv ~/.zshrc ~/.zshrc_$(date -date +"%Y%m%d%s").bak || true
      - ln -s ${DOTFILES_RC}/zshrc ~/.zshrc
