version: "3"
tasks:
  all:
    desc: Install Python package managers and all required packages
    cmds:
      - task: all:deps
      - task: all:packages
  all:deps:
    desc: Install pipx
    status:
      - pipx --version
    cmds:
      - brew install pipx
      - pipx --version
  all:packages:
    desc: Install required Python packages
    cmds:
      - for:
          - checkov
          - ruff
          - awsume
        cmd: zsh -l -c "source ${HOME}/.zshrc ; pipx list | grep -w {{.ITEM}} || pipx install {{.ITEM}}"
