version: "3"
tasks:
  all:
    desc: Install Python package managers and all required packages
    cmds:
      - task: all:deps
      - task: all:packages
  all:deps:
    desc: Install pipx
    cmds:
      - pipx --version || brew install pipx
      - pipx --version
  all:packages:
    desc: Install required Python packages
    cmds:
      - for:
          - pynvim
          - checkov
          - ruff
          - awsume
        cmd: pipx list | grep -w {{.ITEM}} || pipx install {{.ITEM}}
