#!/bin/zsh

# vi: ft=zsh

# -----------------------------------------------------------------------------
# BAU stuff, shortcuts and some string manipulation handlers
# -----------------------------------------------------------------------------

alias more=less
alias ls='ls --color=tty'
alias lsh='ls -lhXG' # Long human readable
alias ll='eza -lTr --icons'
alias sl='ls' # fix annoyingly common typo
alias bashrc='source ~/.bashrc'
alias zshrc='source ~/.zshrc'
alias dos2unix='perl -pi -e "tr/\r//d"'
alias unix2dos='perl -pi -e "s/\n$/\r\n/g"'
alias mac2unix='perl -pi -e "tr/\r/\n/d"'
alias root="sudo su -"
alias igrep='grep -i'
alias mkdir='mkdir -p'
alias hosts='sudo vim /etc/hosts'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias prettyjson='python -m json.tool'
alias dl="cd ~/Downloads"
alias g="git"
alias h="history"
alias python="python3"
alias clear="clear && printf '\n%.0s' {1..$LINES}"
alias untar='tar xvf'
alias pcat='source-highlight --failsafe -f esc --lang-def=makefile.lang --style-file=esc.style -i '

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# @janmoesens ProTip™s (borrowed from jessfraz dotfiles)
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  # shellcheck disable=SC2139,SC2140
  alias "$method"="PERL_LWP_SSL_VERIFY_HOSTNAME=0 lwp-request -m \"$method\""
done

# btop
if command -v btop &>/dev/null 2>&0; then
  alias top="btop"
  alias htop="btop"
fi

# Shortcut for launching chrome from the terminal
alias google-chrome='"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --kiosk'

# Launch Monokle from CLI
alias Monokle='/Applications/Monokle.app/Contents/MacOS/Monokle'

# BFG - Removes large or troublesome blobs like git-filter-branch does,
# but faster, and written in Scala
#
# --> Download it from 'https://rtyley.github.io/bfg-repo-cleaner/'
BFG_PATH="${HOME}/.local/bin/bfg-1.14.0.jar"
[ -f "${BFG_PATH}" ] && alias bfg='java -jar ${BFG_PATH}'

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# URL-encode strings (borrowed from jessfraz dotfiles)
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# silversearch hidden files
alias ag='ag --hidden'

# Git Aliases
#alias rebase="git pull origin master --rebase; git add -A; git rebase --continue; git push origin $(git rev-parse --abbrev-ref HEAD) -f"
alias lg='lazygit'

# Create an alias for awsume to make it accessible from the command line
alias awsume=". awsume"

# -----------------------------------------------------------------------------
# Editor settings
# -----------------------------------------------------------------------------

set -o vi
if command -v vim &>/dev/null 2>&0; then
  export EDITOR=vim
  alias vi="vim"
else
  export EDITOR=vi
  alias vim="vi"
fi

# Neovim
alias vim="nvim"
alias vi="nvim"

# -----------------------------------------------------------------------------
# Kubectl
# -----------------------------------------------------------------------------

# Source Kubectl aliases (https://github.com/ahmetb/kubectl-aliases)
[ -f "${DOTFILES_CONFIG}/kubectl_aliases.txt" ] && source "${DOTFILES_CONFIG}/kubectl_aliases.txt"

# Shortuct for kubectl
alias kubectl="kubecolor"
alias k='kubectl'
alias kc='k ctx'
alias kcd='kubectl config set-context --current --namespace '
alias kevents='kubectl get events --sort-by='\''.metadata.creationTimestamp'\'''

# -----------------------------------------------------------------------------
# Tmux
# -----------------------------------------------------------------------------

# Creates a new tmux session
alias tn='tmux new -s 000_DEFAULT-$(date "+%H%M%S")'

# Attaches tmux to the last session; creates a new session if none exists.
alias t='tmux attach || tn'

# Attaches tmux to a session (example: ta portal)
alias ta='tmux attach -t'

# Lists all ongoing tmux sessions
alias tl='tmux list-sessions'

# tmuxp load shortcut
alias tp='tmuxp load -y'

# EOF
