#!/bin/zsh
# -----------------------------------------------------------------------------
# Handlers and core OS stuff
# -----------------------------------------------------------------------------
# GpG settings
export GPG_TTY="$(tty)"

# Lang & Locale settings
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Format time output just like bash would
export TIMEFMT=$'real\t%E\nuser\t%U\nsys\t%S'

# don't put duplicate lines or lines starting with space in bash history
export HISTCONTROL="ignoredups:erasedups"

# Make some commands not show up in history
export HISTIGNORE="&:ls:cd -:cd:date:* --help:exit:pwd:history:clear:mount:umount:[ \t]*"

# Display settings for KeePassXC (running with AppImage)
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=DP1=1.5 #;DP1=1.5;DP2=1.5;HDMI1=1.5;HDMI2=1.5;VIRTUAL1=1.5;

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=50000000
export HISTFILESIZE="$HISTSIZE"
export SAVEHIST=$HISTSIZE

# Path for tools and utils
export PATH="${PATH}:${HOME}"
export PATH="${PATH}:${HOME}/.local/share/nvim/mason/bin"
export PATH="${PATH}:${HOME}/AppImage"
export PATH="${PATH}:${HOME}/bin"
export PATH="${PATH}:/Applications/WezTerm.app/Contents/MacOS"
export PATH="${PATH}:/opt/bin"
export PATH="${PATH}:/opt/homebrew/bin"
export PATH="${PATH}:/opt/homebrew/opt/socket_vmnet/bin"
export PATH="${PATH}:/opt/homebrew/sbin"
export PATH="${PATH}:/opt/local/bin"
export PATH="${PATH}:/opt/nvim/bin"
[ -d "${DOTFILES_SCRIPTS}" ] && export PATH="$PATH:${DOTFILES_SCRIPTS}::"

# -----------------------------------------------------------------------------
# Terminal colors & display
# -----------------------------------------------------------------------------

# Color settings
export COLORTERM=truecolor

# get some colors on commands with grc
[[ -s "/etc/grc.zsh" ]] && source "/etc/grc.zsh"

# Syntax highlight for LESS command
if command -v source-highlight &>/dev/null 2>&0; then
  export PAGER="less"
  export LESS="-R"
  [ -f "${DOTFILES_SCRIPTS}/src-hilite-lesspipe.sh" ] &&
    export LESSOPEN="| ${DOTFILES_SCRIPTS}/src-hilite-lesspipe.sh %s"
fi

# make less more friendly for non-text input files, see lesspipe(1)
[ -f /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export FONTCONFIG_PATH=/etc/fonts

# Tmux Profile display
export DISABLE_AUTO_TITLE='true'

# -----------------------------------------------------------------------------
# Tools & Utils
# -----------------------------------------------------------------------------

# Enable Docker build kit by default
export DOCKER_BUILDKIT=1
export BUILDKIT_COLORS=run=green:warning=yellow:error=red:cancel=255,165,0
export BUILDKIT_PROGRESS=plain
export KUBE_EDITOR=nvim
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------
export PATH="${PATH}:/usr/local/git/bin"

# -----------------------------------------------------------------------------
# Coding stuff
# -----------------------------------------------------------------------------

# For compilers to find zlib you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"

# For pkg-config to find zlib you may need to set:
export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

export PATH="${PATH}:${HOME}"

# Golang
export GO111MODULE="on"
export GOPATH="${HOME}/go"
export GOBIN="${GOPATH}/bin"
export PATH="$PATH:$GOBIN:$GOROOT/bin"
export PATH="${PATH}:/usr/local/go/bin"

# Lua
eval "$(luarocks path --bin)"

# Ruby
PATH="${PATH}:${HOME}/.gem/ruby/2.7.0/bin"

# HomeBrew
export PATH="/opt/homebrew/opt/openssl@3.0/bin:$PATH"
export DYLD_LIBRARY_PATH="$(brew --prefix)/lib:$DYLD_LIBRARY_PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
#export PATH="${HOMEBREW_PREFIX}/opt/gnu-sed/libexec/gnubin:${PATH}"

# Mise
export PATH="$PATH:~/.local/share/mise/shims"

# Terraform Env
export PATH="${PATH}:${HOME}/.tfenv/bin"

# Rancher
export DOCKER_DEFAULT_PLATFORM=linux/amd64
export PATH="${PATH}:/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin"
export LIMA_HOME="${HOME}/Library/Application Support/rancher-desktop/lima"
export PATH="${PATH}:${HOME}/.rd/bin"

# -----------------------------------------------------------------------------
# EOF
# -----------------------------------------------------------------------------
