#pIf you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to disable auto-setting terminal title.
export DISABLE_AUTO_TITLE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
export DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  zsh-autosuggestions
  zsh-fzf-history-search
)

source ${ZSH}/oh-my-zsh.sh

# User configuration
set -o vi
zstyle ':completion:*:ssh:*' hosts
zmodload zsh/mapfile

# test
# exports from dotfiles
export DOTFILES_HOME="${HOME}/.dotfiles"
export DOTFILES_CONFIG="${DOTFILES_HOME}/etc/config"
export DOTFILES_PROFILE="${DOTFILES_HOME}/etc/profile"
export DOTFILES_RC="${DOTFILES_HOME}/etc/rc"
export DOTFILES_SCRIPTS="${DOTFILES_HOME}/scripts"

source "${DOTFILES_SCRIPTS}/fzf.zsh"
source "${DOTFILES_SCRIPTS}/histdb.zsh"
source "${DOTFILES_PROFILE}/aliases"
source "${DOTFILES_PROFILE}/exports"
source "${DOTFILES_PROFILE}/functions"

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vi'
  export VISUAL='vi'
else
  export EDITOR='nvim'
  export VISUAL='nvim'
fi

# ZSH sqlite-history
source "${HOME}/.oh-my-zsh/custom/plugins/zsh-histdb/sqlite-history.zsh"
autoload -Uz add-zsh-hook

# Zsh Prettier
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2>/dev/null)"
# if [ $? -eq 0 ]; then
# 	eval "$__conda_setup"
# else
# 	if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
# 		. "/opt/anaconda3/etc/profile.d/conda.sh"
# 	else
# 		export PATH="/opt/anaconda3/bin:$PATH"
# 	fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<

##THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="${HOME}/.sdkman"
#[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="${HOME}/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
