# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to disable auto-setting terminal title.
export DISABLE_AUTO_TITLE="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
export DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  zsh-fzf-history-search
)

source "${ZSH}/oh-my-zsh.sh"

# User configuration
set -o vi
zstyle ':completion:*:ssh:*' hosts
zmodload zsh/mapfile

# exports from dotfiles
export DOTFILES_HOME="${HOME}/.dotfiles"
export DOTFILES_CONFIG="${DOTFILES_HOME}/etc/config"
export DOTFILES_PROFILE="${DOTFILES_HOME}/etc/profile"
export DOTFILES_RC="${DOTFILES_HOME}/etc/rc"
export DOTFILES_SCRIPTS="${DOTFILES_HOME}/scripts"

# sourcing dotfiles scripts
source "${DOTFILES_SCRIPTS}/fzf.zsh"
source "${DOTFILES_SCRIPTS}/histdb.zsh"
source "${DOTFILES_PROFILE}/aliases"
source "${DOTFILES_PROFILE}/exports"
source "${DOTFILES_PROFILE}/functions"

# ZSH sqlite-history
source "${HOME}/.oh-my-zsh/custom/plugins/zsh-histdb/sqlite-history.zsh"
autoload -Uz add-zsh-hook

# Zsh Prettier
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

set bindkey '^[[.' clear-screen

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
