# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  all:
    desc: Install all Java requirements and tools
    cmds:
      - task: all:bfg

  all:bfg:
    vars:
      BFG_DOWNLOAD_URL: "https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar"
      BFG_PATH: "${HOME}/.local/bin/bfg-1.14.0.jar"
    desc: Install BFG Repo-Cleaner
    status:
      - test -f "{{.BFG_PATH}}"
    cmds:
      - curl -fsSL --output {{.BFG_PATH}} {{.BFG_DOWNLOAD_URL}}
      - java -jar {{.BFG_PATH}} --version
